apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki-mysql
  template:
    metadata:
      labels:
        app: mediawiki-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "mediawiki"
        ports:
        - containerPort: 3306
