apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment2
  template:
    metadata:
      labels:
        app: deployment2
    spec:
      containers:
      - name: server1
        image: python:3.11-slim
        command: ["python", "-m", "http.server", "5002"]
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: deployment2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
