apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: envoy-ratelimit
    descriptors:
      - key: path
        value: /httpbin
        rate_limit:
          unit: second
          requests_per_unit: 2
      - key: path
        value: /nginx
        rate_limit:
          unit: minute
          requests_per_unit: 5
