apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: envoy-ratelimit
    descriptors:
      # - key: path
      #   value: /httpbin
      #   rate_limit:
      #     unit: second
      #     requests_per_unit: 2
      - key: generic_key
        value: httpbin
        rate_limit:
          unit: second
          requests_per_unit: 2
      - key: generic_key
        value: nginx
        rate_limit:
          unit: minute
          requests_per_unit: 5
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: envoy-ratelimit
    descriptors:
      - key: generic_key
        value: httpbin
        rate_limit:
          unit: second
          requests_per_unit: 2
      - key: generic_key
        value: nginx
        rate_limit:
          unit: minute
          requests_per_unit: 5

