apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment1
  template:
    metadata:
      labels:
        app: deployment1
    spec:
      containers:
      - name: server1
        image: python:3.11-slim
        command: ["python", "-m", "http.server", "5001"]
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: deployment1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
