apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 8080;
      location / {
           root /usr/share/nginx/html;
           index index.html;
      }
    }
