apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      # --- Backend container: httpbin ---
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80

      # --- Backend container: nginx ---
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d

      # --- Envoy sidecar ---
      - name: envoy
        image: envoyproxy/envoy:v1.31.2
        args: ["-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
        ports:
        - containerPort: 10000
        - containerPort: 9901
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
      - name: nginx-conf
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: service
metadata: 
  name: nginx_service
spec:
  type: ClusterIP
  selector:
    app: exampleapp
  ports:
  - name: http
    port: 80
    targetport: 8080
